#!/bin/bash
# USAGE : change folder icon to reflect content
# Ex, folder-pictures if folder has lots of pictures

######## INIT VARIABLES ########
ARG="$1"
DEPTH="2"

######## SCRIPT ########

# Count how much of each type in the folder
COUNT_DOC=$(find "$ARG" -maxdepth $DEPTH -not -type d | grep -iE  '.(pdf|txt|odt|doc|ppt|xls|docx|pptx|xlsx)$' | wc -l)
COUNT_PICTURES=$(find "$ARG" -maxdepth $DEPTH -not -type d | grep -iE  '.(png|jpg|webp|gif)$' | wc -l)
COUNT_MUSIC=$(find "$ARG" -maxdepth $DEPTH -not -type d | grep -iE  '.(ogg|mp3)$' | wc -l)
COUNT_VIDEOS=$(find "$ARG" -maxdepth $DEPTH -not -type d | grep -iE  '.(mp4)$' | wc -l)

# Group
declare -a ar=($COUNT_DOC $COUNT_PICTURES $COUNT_MUSIC $COUNT_VIDEOS)

# Get highest
IFS=$'\n' sorted=($(sort -nr <<<"${ar[*]}"))
HIGHEST=${sorted[0]}

# Find which one it belongs to
# And set appropriate icon
case $HIGHEST in
	$COUNT_DOC) ico="folder-documents" ;;
	$COUNT_PICTURES) ico="folder-pictures" ;;
	$COUNT_MUSIC) ico="folder-music" ;;
	$COUNT_VIDEOS) ico="folder-videos" ;;
esac

echo "setting $ico"
gio set -t string "$ARG" metadata::custom-icon-name $ico && \
notify-send --app-name "Set icon" --icon $ico "Successfully set icon folder! Refresh file manager view to see new icon :)"

#publicshare recent insync-folder user-home download
